extend type Query {
    problem(id: ID!): Problem
        @filterOrder
        @filterParticipated
        @filterScopeStarted
        @filterVisibility
        @inferScope
        @retrieve(collection: "problem")
        @ifAuth
    problems(
        scope: ID!
        where: ProblemWhereInput
        orderBy: ProblemOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Problem]!
        @filterOrder
        @filterParticipated
        @filterScopeStarted
        @inferScope(array: true)
        @ifAuth
}

extend type Mutation {
    createProblem(scope: ID!): Problem
        @inferScope
        @ifAdmin
        @ifAuth
    updateProblem(
        id: ID!
        data: ProblemUpdateInput
    ): Problem
        @ifAdmin
        @ifAuth
    deleteProblem(id: ID!): Problem
        @ifAdmin
        @ifAuth
    uploadTestcaseFile(
        id: ID!
        idx: Int!
        file: Upload!
        type: TestcaseFileType!
    ): File
        @ifAdmin
        @ifAuth
}

enum TestcaseFileType {
    IN
    OUT
}

input ProblemWhereInput {
    id: ID
    creator: String
    title_contains: String
    OR: [ProblemWhereInput!]
    AND: [ProblemWhereInput!]
    hasStory: Boolean
    isReady: Boolean
    visible: Boolean
    createdAt_lte: DateTime
    createdAt_gte: DateTime
    updatedAt_lte: DateTime
    updatedAt_gte: DateTime
    tags: [String!]
    order: Int
    order_lte: Int
    order_gte: Int
}

enum ProblemOrderByInput {
    title_ASC
    title_DESC
    nAccepted_ASC
    nAccepted_DESC
    nAttempted_ASC
    nAttempted_DESC
    createdAt_ASC
    createdAt_DESC
    updatedAt_ASC
    updatedAt_DESC
    order_ASC
    order_DESC
}

input ExampleUpdateInput {
    input: String!
    output: String!
}

input TestcaseUpdateInput {
    time: Int!
    memory: Int!
    point: Int!
}

input ProblemUpdateInput {
    scope: ID
    title: String
    story: String
    background: String
    description: String
    inputFormat: String
    outputFormat: String
    tips: String
    stdAnswer: String
    examples: [ExampleUpdateInput!]
    testcases: [TestcaseUpdateInput!]
    spj: String
    tags: [String!]
    visible: Boolean
}

type Example {
    input: String!
    output: String!
}

type Testcase {
    time: Int!
    memory: Int!
    point: Int!
}

type Problem {
    id: ID!
    scope: Scope!
        @filterVisibility
    creator: User!
    title: String!
    story: String!
    background: String!
    description: String!
    inputFormat: String!
    outputFormat: String!
    tips: String!
    stdAnswer: String!
    examples: [Example!]!
    testcases: [Testcase!]!
    spj: String!
    tags: [String!]!
    visible: Boolean!
    submissions(
        where: SubmissionWhereInput
        orderBy: SubmissionOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Submission!]!
        @filterScopeEnded
    createdAt: String!
    updatedAt: String!
    order: Int!
}
