extend type Query {
    scope(id: ID!): Scope @auth
    scopes(
        where: ScopeWhereInput
        orderBy: ScopeOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Scope]! @auth
    sortedParticipants(id: ID!): [Participant!] @auth
}

extend type Mutation {
    createScope: Scope! @auth @admin
    updateScope(
        id: ID!
        data: ScopeUpdateInput
    ): Scope @auth @admin
    deleteScope(id: ID!): Scope @auth @admin
}

input ScopeWhereInput {
    id: ID
    creator: String
    title_contains: String
    OR: [ScopeWhereInput!]
    AND: [ScopeWhereInput!]
    isSorted: Boolean
    isLinear: Boolean
    isContest: Boolean
    visible: Boolean
    from_lte: DateTime
    from_gte: DateTime
    to_lte: DateTime
    to_gte: DateTime
    createdAt_lte: DateTime
    createdAt_gte: DateTime
    updatedAt: String
    updatedAt_lte: DateTime
    updatedAt_gte: DateTime
}

enum ScopeOrderByInput {
    title_ASC
    title_DESC
    from_ASC
    from_DESC
    to_ASC
    to_DESC
    createdAt_ASC
    createdAt_DESC
    updatedAt_ASC
    updatedAt_DESC
}

input ScopeUpdateInput {
    title: String
    isSorted: Boolean
    isLinear: Boolean
    skippable: Int
    isContest: Boolean
    contestMode: String
    description: String
    visible: Boolean
    from: Int
    to: Int
}

type Scope {
    id: ID!
    creator: User!
    title: String!
    problems(
        scope: ID!
        where: ProblemWhereInput
        orderBy: ProblemOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Problem!]!
    isSorted: Boolean!
    participants(sorted: Boolean! = false): [Participant!]!
    isLinear: Boolean!
    skippable: Int
    isContest: Boolean!
    contestMode: String
    description: String!
    visible: Boolean!
    from: DateTime
    to: DateTime
    createdAt: String!
    updatedAt: String!
}
