extend type Query {
    submission(id: ID!): Submission
        @filterOrder
        @filterParticipated
        @filterScopeEnded
        @inferScope
        @inferProblem
        @retrieve(collection: "submission")
        @ifAuth
    submissions(
        problem: ID!
        where: SubmissionWhereInput
        orderBy: SubmissionOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Submission]!
        @filterOrder
        @filterParticipated
        @filterScopeEnded
        @inferScope(array: true)
        @inferProblem(array: true)
        @ifAuth
}

extend type Mutation {
    createSubmission(
        problem: ID!
        code: String!
        language: String!
    ): Submission
        @ifOrder
        @ifParticipated
        @ifScopeStarted
        @ifScopeNotEnded
        @inferScope
        @inferProblem
        @ifAuth
}

input SubmissionWhereInput {
    id: ID
    user: String
    OR: [SubmissionWhereInput!]
    AND: [SubmissionWhereInput!]
    language: String
    status: SubmissionStatus
    score_lte: Int
    score_gte: Int
    createdAt_lte: DateTime
    createdAt_gte: DateTime
}

enum SubmissionOrderByInput {
    language_ASC
    language_DESC
    score_ASC
    score_DESC
    createdAt_ASC
    createdAt_DESC
}

enum TestcaseStatus {
    JUDGING,
    ACCEPTED,
    WRONG_ANSWER,
    PARTIALLY_CORRECT,
    TIME_LIMIT_EXCEEDED,
    MEMORY_LIMIT_EXCEEDED,
    OUTPUT_LIMIT_EXCEEDED,
    RUNTIME_ERROR,
    SPECIAL_JUDGE_ERROR,
    COMPILE_ERROR,
    UNKNOWN_ERROR,
}

type TestcaseResult {
    time: Int!
    memory: Int!
    point: Int!
    status: TestcaseStatus!
}

enum SubmissionStatus {
    JUDGING,
    ACCEPTED,
    NOT_ACCEPTED,
    ERROR,
}

type Submission {
    id: ID!
    user: User!
    problem: Problem!
        @filterParticipated
        @filterScopeStarted
        @filterVisibility
    code: String
    language: String!
    status: SubmissionStatus!
    score: Int!
    detail: [TestcaseResult!]!
    createdAt: String!
    updatedAt: String!
}
