extend type Query {
    token(id: ID!): Token
    # tokens: Searching is unsupported
    user(id: ID!): User @auth
    users(
        where: UserWhereInput
        orderBy: UserOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [User]! @auth
}

extend type Mutation {
    createToken(
        id: ID!
        pass: String!
    ): Token!
    deleteToken(id: ID!): Token
    createUser(
        username: String!
        pass: String!
    ): User! # TODO: CAPTCHA
    updateUser(
        id: ID!
        data: UserUpdateInput!
    ): User @auth
    setUserAdmin(
        id: ID!
        isAdmin: Boolean!
    ): User @auth @admin
    deleteUser(
        id: ID!
    ): User @auth @admin
    uploadAvatar(
        id: ID!
        file: Upload!
    ): File @auth
}

input UserWhereInput {
    id: ID
    username: [String!]
    acceptedProblems: [ID!]
    attemptedProblems: [ID!]
    isAdmin: Boolean
    scopes: [ID!]
    problems: [ID!]
    createdAt_lte: String
    createdAt_gte: String
    updatedAt_lte: String
    updatedAt_gte: String
    lastSubmitAt_lte: String
    lastSubmitAt_gte: String
}

enum UserOrderByInput {
    username_ASC
    username_DESC
    createdAt_ASC
    createdAt_DESC
    updatedAt_ASC
    updatedAt_DESC
    lastSubmitAt_ASC
    lastSubmitAt_DESC
}

input UserUpdateInput {
    username: String
    introduction: String
}

type Token {
    id: ID!
    user: User!
}

type User {
    id: ID!
    username: String!
    introduction: String!
    acceptedProblems(
        scope: ID!
        where: ProblemWhereInput
        orderBy: ProblemOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Problem!]!
    attemptedProblems(
        scope: ID!
        where: ProblemWhereInput
        orderBy: ProblemOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Problem!]!
    isAdmin: Boolean!
    scopes(
        where: ScopeWhereInput
        orderBy: ScopeOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Scope!]!
    participants: [Participant!]!
    submissions(
        scope: ID!
        where: SubmissionWhereInput
        orderBy: SubmissionOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Submission!]!
    problems(
        scope: ID!
        where: ProblemWhereInput
        orderBy: ProblemOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [Problem!]!
    createdAt: String!
    updatedAt: String!
    lastSubmitAt: String!
}
