extend type Query {
    token(id: ID!): Token
    # tokens: Searching is unsupported
    user(id: ID!): User
        @ifAuth
    users(
        where: UserWhereInput
        orderBy: UserOrderByInput
        skip: Int
        first: Int
        last: Int
    ): [User]!
        @ifAuth
}

extend type Mutation {
    createToken(
        username: String!
        pass: String!
    ): Token!
    deleteToken(id: ID!): Token
    createRootUser(
        token: ID!
        pass: String!
    ): User!
    createUser(
        username: String!
        pass: String!
    ): User! # TODO: CAPTCHA
    updateUser(data: UserUpdateInput!): User
        @ifAuth
    setUserAdmin(
        id: ID!
        isAdmin: Boolean!
    ): User
        @ifAdmin
        @ifAuth
    deleteUser(
        id: ID!
    ): User
        @ifAdmin
        @ifAuth
    uploadAvatar(file: Upload!): File
        @ifAuth
}

input UserWhereInput {
    id: ID
    username_contains: String
    OR: [UserWhereInput!]
    AND: [UserWhereInput!]
    acceptedProblems_some: ProblemWhereInput
    attemptedProblems_some: ProblemWhereInput
    isAdmin: Boolean
    scopes_some: ScopeWhereInput
    problems_some: ProblemWhereInput
    createdAt_lte: DateTime
    createdAt_gte: DateTime
    updatedAt_lte: DateTime
    updatedAt_gte: DateTime
    lastSubmitAt_lte: DateTime
    lastSubmitAt_gte: DateTime
}

enum UserOrderByInput {
    username_ASC
    username_DESC
    createdAt_ASC
    createdAt_DESC
    updatedAt_ASC
    updatedAt_DESC
    lastSubmitAt_ASC
    lastSubmitAt_DESC
}

input UserUpdateInput {
    username: String
    introduction: String
}

type Token {
    id: ID!
    user: User!
}

type User {
    id: ID!
    username: String!
    introduction: String!
    isAdmin: Boolean!
    participants: [Participant!]!
    createdAt: String!
    updatedAt: String!
    lastSubmitAt: String!
}
